#!/usr/bin/env sh

export TARGETARCH=$1
export DOTNET_SDK_VERSION=$2

echo "\n# Installing .NET Core SDK v$2 for $TARGETARCH\n"

if [ "$TARGETARCH" = "amd64" ]
then 
    export ARCH=x64;
else
    export ARCH=arm64;
fi

export URL=https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/dotnet-sdk-$DOTNET_SDK_VERSION-linux-$ARCH.tar.gz
echo $URL
curl -SL --output dotnet.tar.gz $URL
if [ "$TARGETARCH" = "amd64" ]
then 
    dotnet_sha512='9d70b4a8a63b66da90544087199a0f681d135bf90d43ca53b12ea97cc600a768b0a3d2f824cfe27bd3228e058b060c63319cd86033be8b8d27925283f99de958'
else 
    dotnet_sha512='565fe5cbc2c388e54b3ee548d5b98e1fd85d920ceeeb5475a2bf2daa7f090fc925d8afef19b2b76973af439fbb749c6996711790287eafd588e4d916a016e84c'
fi
echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c -
mkdir -p /usr/share/dotnet
tar -zxf dotnet.tar.gz -C /usr/share/dotnet
rm dotnet.tar.gz
ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

curl -SL --output /usr/share/dotnet/sdk/$DOTNET_SDK_VERSION/nuGetPackagesArchive.lzma https://dotnetcli.azureedge.net/dotnet/Sdk/$DOTNET_SDK_VERSION/nuGetPackagesArchive.lzma
lzma_sha512='09c0d7da8da38ed486f53c052f7dd87bfb3f3b9e32300b69b424566395b32422cecbb27db37560d604a89f6463879b40ef6fa5d1ea8fe48cf832aa6f4fa0f331'
echo "$lzma_sha512 /usr/share/dotnet/sdk/$DOTNET_SDK_VERSION/nuGetPackagesArchive.lzma" | sha512sum -c -

## Trigger first run experience by running arbitrary cmd to populate local package cache
dotnet help