name: Build

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "0 0 * * *" # midnight daily

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build docker image

    steps:
      - uses: actions/checkout@v2
      # - uses: satackey/action-docker-layer-caching@v0.0.11
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build the image
        run: make
        env:
          PLATFORMS: linux/arm64,linux/amd64
          DOCKER_BUILDKIT: 1
