name: Build

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    name: Build docker image

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build the image
        uses: docker/build-push-action@v4
        with:
          platforms: linux/arm64,linux/amd64
          tags: cucumber/cucumber-build:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
